### ISSUE TITLE
allow installing using specific git commit

### ISSUE THREAD

**Issue by adrian-gierakowski** [basherpm/basher#65]
the format could be: `site/package#commitsha` (similar to `npm`)

**Comment by juanibiapina** [comment]
This currently works with branches and tags, but not refs, because it uses the `-b` option of git clone. Does it solve your problem? If it doesn't, we would need to change the clone implementation to checkout the specific ref.

**Comment by adrian-gierakowski** [comment]
Hi @juanibiapina, I used the branch approach in the end, but I'd prefer to be able to pin the install to specific commit in cases when the installed package is meant to be used in production.

**Comment by juanibiapina** [comment]
Tags are the obvious solution to this, since it allows you to tag actual versions of packages. Nevertheless, I can accept a PR for this if it works well. Problems I foresee:

- A shallow clone cannot be used anymore because the commit sha can appear anywhere in the history
- I don't see a mechanism in git itself to do this (like the `-b` option for branches and tags).
- the `upgrade` command needs to take into consideration if you want to always keep that specific ref

`basher` was never designed for a use case of a dependency manager, but more and more I get requests to support this kind of functionality.

**Comment by juanibiapina** [comment]
Closing because it's inactive.

**Comment by adrian-gierakowski** [comment]
@juanibiapina not a problem. I've since switched to using [nix](https://nixos.org/) for all my package management needs which allows me to pin git repos using a commit sha.
